---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
  namespace: pacman-052
type: Opaque 
data:
  database-admin-name: Y2x5ZGU=
  database-admin-password: Y2x5ZGU=
  database-name: cGFjbWFu
  database-password: cGlua3k=
  database-user: Ymxpbmt5
  keyfile-value: cjNkaDR0Cg==
---